# Generated by Django 5.1.2 on 2024-11-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sddkd_app', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
